# Site settings
title: Zi's website
url: https://weirdkittyz.github.io/
skills: "Hungry Scatterer - Amateur Artist & Photographer"



# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7d8a7b
  primary-rgb: "125, 138, 123"
  secondary: 556b51
  secondary-dark: 41573e

# Footer settings
footer:
  copyright: Yijia Zi
  social: Social


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Email
    url: mailto://ziy2@mcmaster.ca
    icon: fas fa-envelope
  - title: GitHub
    url: https://github.com/WeirdKittyZ
    icon: fab fa-github
  - title: Instagram
    url: https://www.instagram.com/z._1896528?igsh=aWh5ZzlnZTJoM3Rp&utm_source=qr
    icon: fab fa-instagram
  - title: Linkedin
    url: www.linkedin.com/in/yijia-zi-644634178
    
# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
