# Site settings
title: Zi's website
url: https://weirdkittyz.github.io/
skills: "Hungry Scatterer - Amateur Artist & Photographer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: faf5ab
  primary-rgb: "243,181,207"
  secondary: 69c8c3
  secondary-dark: 3cbeb7

# Footer settings
footer:
  copyright: Yijia Zi
  social: Social


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: email
    url: mailto://ziy2@mcmaster.ca
  - title: gitHub
    url: https://github.com/WeirdKittyZ
  - title: instagram
    url: https://www.instagram.com/z._1896528?igsh=aWh5ZzlnZTJoM3Rp&utm_source=qr
  - title: linkedin
    url: https://wwww.linkedin.com/in/yijia-zi-644634178
    
# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
